### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by wumbomumbo** [ojdkbuild/contrib_jdk11u-arm32-ci#1]
Please if its possible add Windows 10 Support (and/or Windows RT) this would be amazing because the Surface RT and 2 run on ARM32 CPU's which there is no download for.

**Comment by ojdkbuild** [comment]
Hi, sorry, this is not possible, ARM32 support in OpenJDK can be built
only for Linux. For ARM64 Windows devices jdk17 is going to support
ARM64, but not ARM32.

**Comment by wumbomumbo** [comment]
Ah ok understandable, thanks for saying, good thing that Linux is slowly getting more usable on the Surface RT.
